.

diff --git a/bin/git-rebase-i-amend-head b/bin/git-rebase-i-amend-head
--- a/bin/git-rebase-i-amend-head
+++ b/bin/git-rebase-i-amend-head
@@ -41,15 +41,19 @@ while [[ $# -gt 0 ]]; do
 done
 
 if [ -z "${1-}" ] && [ -d .git/rebase-merge ]; then
-  source_commit_input=$(git-rebase-i-get-orig-commit)
+  # This is expected to fail for custom merge commands that don't have a -C <orig_commit> line, for example
+  # It is required for git-rebase-i-amend-merge-reapply-orig-changes, but not for git-rebase-i-amend-merge-add-details
+  source_commit_input=$(git-rebase-i-get-orig-commit 2>/dev/null || true)
 else
   source_commit_input=${1-}
 fi
 
 #════════════════════════════════════════════════════════════════════════════════════════════════════
 
-source_commit=$(git rev-parse --verify "$source_commit_input"^{commit})
-source_short=$(git rev-parse --short $source_commit)
+if [ -n "${source_commit_input-}" ]; then
+  source_commit=$(git rev-parse --verify "$source_commit_input"^{commit})
+  source_short=$(git rev-parse --short $source_commit)
+fi
 
 # The commit we are amending, which can only be HEAD
 head=$(git rev-parse HEAD)
@@ -58,7 +62,9 @@ head_short=$(git rev-parse --short HEAD)
 #════════════════════════════════════════════════════════════════════════════════════════════════════
 
 if git-is-merge-commit $head; then
-  git-rebase-i-amend-merge-reapply-orig-changes
+  if [ -n "${source_commit-}" ]; then
+    git-rebase-i-amend-merge-reapply-orig-changes
+  fi
   git-rebase-i-amend-merge-add-details
 else
   git-commit-amend-copy
diff --git a/bin/git-rebase-i-get-orig-commit b/bin/git-rebase-i-get-orig-commit
--- a/bin/git-rebase-i-get-orig-commit
+++ b/bin/git-rebase-i-get-orig-commit
@@ -118,10 +118,13 @@ fi
 # A more strict regex would be [0-9a-f]{7,40}
 if [[ $line =~ ^(m|merge)\ -C\ ([0-9a-f]+) ]]; then
   original_commit=${BASH_REMATCH[2]}
-  $verbose && echo "🔁 Found original merge commit: $original_commit"
+  $verbose && echo >&2 "🔁 Found original merge commit: $original_commit"
+#elif [[ $line =~ ^(m|merge)\  ]]; then
+#  echo >&2 "Could not extract original commit id from line: $line"
+#  exit
 elif [[ $line =~ ^(p|pick|e|edit|r|reword)\ ([0-9a-f]+) ]]; then
   original_commit=${BASH_REMATCH[2]}
-  $verbose && echo "🔁 Found original commit: $original_commit"
+  $verbose && echo >&2 "🔁 Found original commit: $original_commit"
 else
   echo >&2 "❌ Could not extract previous commit from line: $line"
   exit 1
