make git-split-commit-by-specificity use:  git-detect-file-specificity --show-matches always "$file"
add git-verify-commit-common-only

diff --git a/bin/git-current-branch b/bin/git-current-branch
--- a/bin/git-current-branch
+++ b/bin/git-current-branch
@@ -24,7 +24,7 @@ while (( "$#" )); do
 #      ;;
 
     -*|--*=)
-      echo "Error: Unsupported flag $1" >&2
+      echo "Error: Unsupported option $1" >&2
       exit 1
       ;;
     *)
