Misc.

diff --git a/bin/git-commit-modify b/bin/git-commit-modify
--- a/bin/git-commit-modify
+++ b/bin/git-commit-modify
@@ -18,7 +18,10 @@
 # GIT_COMMITTER_DATE='1232532483 -0800' git commit-modify
 
 # Overwrite both author and committer date (useful when you are both author and committer):
-# date='2009-01-21 02:08:05' git commit-modify ; gsf
+# git_date='2009-01-21 02:08:05' git commit-modify
+
+# Overwrite both author and committer email (useful when you are both author and committer):
+# git_email='you@adifferent.org' git commit-modify
 
 # Note that this only rewrites existing commits, so if you want to cause your next commit to have a date or other attribute other than what it normally would have, you still have to commit it normally first before you can use git-commit-modify.
 
@@ -32,7 +35,7 @@
 #---------------------------------------------------------------------------------------------------
 # Dependencies/lib
 
-pushd "$(git rev-parse --show-cdup)"
+pushd "$(git rev-parse --show-cdup)" > /dev/null
 
 . "$(git --exec-path)/git-sh-setup"
 
@@ -75,14 +78,31 @@ preserved_GIT_COMMITTER_NAME="$GIT_COMMITTER_NAME"
 preserved_GIT_COMMITTER_EMAIL="$GIT_COMMITTER_EMAIL"
 preserved_GIT_COMMITTER_DATE="$GIT_COMMITTER_DATE"
 
+while test $# != 0
+do
+	case "$1" in
+  # TODO: Split this out to its own stand-alone command?
+	--show-info-only)
+		show_info_only=1
+		;;
+	esac
+	shift
+done
+
 #---------------------------------------------------------------------------------------------------
 # Record current (pre-change) commit data
 
-echo GIT_AUTHOR_DATE=$GIT_AUTHOR_DATE
-echo GIT_COMMITTER_DATE=$GIT_COMMITTER_DATE
-
 eval "$(get_author_ident_from_commit    $rev)"
 eval "$(get_committer_ident_from_commit $rev)"
+
+if test "$show_info_only" = "1" ; then
+  echo GIT_AUTHOR_EMAIL=$GIT_AUTHOR_EMAIL
+  echo GIT_AUTHOR_DATE=$GIT_AUTHOR_DATE
+  #echo GIT_COMMITTER_NAME=$GIT_COMMITTER_NAME
+  echo GIT_COMMITTER_EMAIL=$GIT_COMMITTER_EMAIL
+  echo GIT_COMMITTER_DATE=$GIT_COMMITTER_DATE
+  exit 0
+fi
 
 # User-supplied values should overwride pre-existing values
 test ! -z "$preserved_GIT_AUTHOR_NAME"     && GIT_AUTHOR_NAME="$preserved_GIT_AUTHOR_NAME"
@@ -92,17 +112,20 @@ test ! -z "$preserved_GIT_COMMITTER_NAME"  && GIT_COMMITTER_NAME="$preserved_GIT
 test ! -z "$preserved_GIT_COMMITTER_EMAIL" && GIT_COMMITTER_EMAIL="$preserved_GIT_COMMITTER_EMAIL"
 test ! -z "$preserved_GIT_COMMITTER_DATE"  && GIT_COMMITTER_DATE="$preserved_GIT_COMMITTER_DATE"
 
-test ! -z "$date" && GIT_AUTHOR_DATE="$date"
-test ! -z "$date" && GIT_COMMITTER_DATE="$date"
+test ! -z "$git_email" &&    GIT_AUTHOR_EMAIL="$git_email"
+test ! -z "$git_email" && GIT_COMMITTER_EMAIL="$git_email"
+
+test ! -z "$git_date" &&    GIT_AUTHOR_DATE="$git_date"
+test ! -z "$git_date" && GIT_COMMITTER_DATE="$git_date"
 
 echo "After:"
+echo GIT_AUTHOR_EMAIL=$GIT_AUTHOR_EMAIL
 echo GIT_AUTHOR_DATE=$GIT_AUTHOR_DATE
 echo GIT_COMMITTER_DATE=$GIT_COMMITTER_DATE
 
 # TODO: file_list=`git list files from commit`
 git cat-file commit "$rev" | sed "1,/^$/d" > .git/git-commit-modify-message
-cat .git/git-commit-modify-message
-
+#cat .git/git-commit-modify-message
 
 #---------------------------------------------------------------------------------------------------
 # Re-commit
@@ -118,17 +141,19 @@ GIT_AUTHOR_DATE="$GIT_AUTHOR_DATE"         \
 GIT_COMMITTER_NAME="$GIT_COMMITTER_NAME"   \
 GIT_COMMITTER_EMAIL="$GIT_COMMITTER_EMAIL" \
 GIT_COMMITTER_DATE="$GIT_COMMITTER_DATE"   \
-git commit $file_list --no-verify -F .git/git-commit-modify-message || failed=t
+git commit $file_list --quiet --no-verify -F .git/git-commit-modify-message || failed=t
 
 #---------------------------------------------------------------------------------------------------
 # Clean up
 
-if test $failed = t ; then
-  echo "Detected failure!"
-else
-  echo "Success"
-fi
-
 rm .git/git-commit-modify-message
 
-popd
+popd > /dev/null
+
+if test $failed = t ; then
+  echo "Detected failure!"
+  exit 1
+else
+  #echo "Success"
+  exit 0
+fi
