Add git-rebase-i-amend-merge-reapply-orig-changes
Update git-rebase-i-get-orig-commit to work for merge commits

diff --git a/bin/git-rebase-i-amend-head b/bin/git-rebase-i-amend-head
--- a/bin/git-rebase-i-amend-head
+++ b/bin/git-rebase-i-amend-head
@@ -1,12 +1,13 @@
 #!/usr/bin/env bash
 
 set -euo pipefail
+trap 'echo "❌ Error at line $LINENO: $BASH_COMMAND"' err
 
 #════════════════════════════════════════════════════════════════════════════════════════════════════
 
 usage() {
   cat - <<End >&2
-Usage: $(basename "$0")
+Usage: $(basename "$0") [<source-commit>]
 
 Copy some details from other commit
 
@@ -21,7 +22,7 @@ If HEAD is a merge commit, this executes git-rebase-i-amend-merge-add-details.
 Otherwise, this executes git-commit-amend-copy.
 
 Example:
-  git rebase -i --exec 'git-commit-amend-head'
+  git rebase -i --exec 'git-rebase-i-amend-head'
 
 See also: git-rebase-i-amend-merge-add-details, git-commit-amend-copy
 End
@@ -57,6 +58,7 @@ head_short=$(git rev-parse --short HEAD)
 #════════════════════════════════════════════════════════════════════════════════════════════════════
 
 if git-is-merge-commit $head; then
+  git-rebase-i-amend-merge-reapply-orig-changes
   git-rebase-i-amend-merge-add-details
 else
   git-commit-amend-copy
