.

diff --git a/sh/git_commands b/sh/git_commands
--- a/sh/git_commands
+++ b/sh/git_commands
@@ -901,6 +901,15 @@ function  gci() {
 	pass_through_opts=""
 	while (( "$#" )); do
 		case "$1" in
+      -c|--reedit-message)
+        if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+          pass_through_opts="$pass_through_opts $1 $2"
+          shift 2
+        else
+          echo "Error: Argument for $1 is missing" >&2
+          exit 1
+        fi
+        ;;
 			-*|--*=) # unknown opts
 				pass_through_opts="$pass_through_opts $1"
 				shift
@@ -912,7 +921,7 @@ function  gci() {
 		esac
 	done
 	eval set -- "$positional_args"
-	echo pass_through_opts: ${pass_through_opts}
+	#echo pass_through_opts: ${pass_through_opts}
   #echo "$@"
 
   if [ -n "$1" ]; then
@@ -925,7 +934,7 @@ function  gci() {
 
     readarray -t files < <(git ls-files "$@")
 		#echo files: "${files[@]}"
-		eval set -- "$files"
+		eval set -- "${files[@]}"
   else
     # If no files were given, we can't use ls-files.
     # If partial contents of files have been staged, then we *must not* pass a list of files to git
