.

diff --git a/sh/git_commands b/sh/git_commands
--- a/sh/git_commands
+++ b/sh/git_commands
@@ -910,6 +910,15 @@ function  gci() {
           exit 1
         fi
         ;;
+      --fixup)
+        if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+          pass_through_opts="$pass_through_opts $1 $2"
+          shift 2
+        else
+          echo "Error: Argument for $1 is missing" >&2
+          exit 1
+        fi
+        ;;
 			-*|--*=) # unknown opts
 				pass_through_opts="$pass_through_opts $1"
 				shift
@@ -922,7 +931,7 @@ function  gci() {
 	done
 	eval set -- "$positional_args"
 	#echo pass_through_opts: ${pass_through_opts}
-  #echo "$@"
+  #echo positional_args: "$@"
 
   if [ -n "$1" ]; then
     # This is so that I can use wildcards without worrying that it might match a file that's not in
